# Stage 1: Base image with common dependencies
FROM nvcr.io/nvidia/cuda:12.4.1-cudnn-runtime-ubuntu22.04 as base

# Prevents prompts from packages asking for user input during installation
ENV DEBIAN_FRONTEND=noninteractive
# Prefer binary wheels over source distributions for faster pip installations
ENV PIP_PREFER_BINARY=1
# Ensures output from python is printed immediately to the terminal without buffering
ENV PYTHONUNBUFFERED=1
# Speed up some cmake builds
ENV CMAKE_BUILD_PARALLEL_LEVEL=8

# Install Python, git and other necessary tools
RUN apt-get update && apt-get install -y \
    python3.10 \
    python3-pip \
    git \
    wget \
    libgl1 \
    && ln -sf /usr/bin/python3.10 /usr/bin/python \
    && ln -sf /usr/bin/pip3 /usr/bin/pip

# Install torch, xformers which matches to the cuda version
RUN pip install torch torchvision torchaudio xformers --index-url https://download.pytorch.org/whl/cu124

# Clean up to reduce image size
RUN apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/*

# Install comfy-cli
RUN pip install comfy-cli

# Install ComfyUI
RUN /usr/bin/yes | comfy --workspace /comfyui install --cuda-version 12.4 --nvidia --version 0.3.33 --skip-manager

# Change working directory to ComfyUI
WORKDIR /comfyui

# Pull latest comfyui
RUN git pull origin master

# Install runpod
RUN pip install runpod requests

# Support for the network volume
ADD src/extra_model_paths.yaml ./

# Go back to the root
WORKDIR /

# Add scripts
ADD src/start.sh src/restore_snapshot.sh src/rp_handler.py test_input.json ./
RUN chmod +x /start.sh /restore_snapshot.sh

# Optionally copy the snapshot file
ADD *snapshot*.json /

# Restore the snapshot to install custom nodes
RUN /restore_snapshot.sh

# Start container
CMD ["/start.sh"]

# Stage 2: Download models
FROM base as downloader

ARG MODEL_TYPE

# Change working directory to ComfyUI
WORKDIR /comfyui

# Create necessary directories
RUN mkdir -p models/checkpoints models/vae models/clip models/unet models/controlnet

COPY models/clip/clip_g.safetensors models/clip/clip_g.safetensors
COPY models/clip/clip_l.safetensors models/clip/clip_l.safetensors
COPY models/clip/t5xxl_fp8_e4m3fn.safetensors models/clip/t5xxl_fp8_e4m3fn.safetensors
# COPY models/clip/t5xxl_fp16.safetensors models/clip/t5xxl_fp16.safetensors

COPY models/checkpoints/sd3.5_large.safetensors models/checkpoints/sd3.5_large.safetensors
COPY models/checkpoints/sd3.5_large_turbo.safetensors models/checkpoints/sd3.5_large_turbo.safetensors

COPY models/controlnet/sd3.5_large_controlnet_canny.safetensors models/controlnet/sd3.5_large_controlnet_canny.safetensors
COPY models/controlnet/sd3.5_large_controlnet_depth.safetensors models/controlnet/sd3.5_large_controlnet_depth.safetensors

COPY models/loras models/loras

# # Stage 3: Final image
#FROM base as final

# # Copy models from stage 2 to the final image
#COPY --from=downloader /comfyui/models /comfyui/models

WORKDIR /comfyui

RUN pip install -r requirements.txt

RUN git clone https://github.com/cubiq/ComfyUI_essentials.git /comfyui/custom_nodes/ComfyUI_essentials && \
    pip install colour-science pixeloe transparent-background

RUN git clone https://github.com/ltdrdata/ComfyUI-Impact-Pack.git /comfyui/custom_nodes/ComfyUI-Impact-Pack && \
    cd /comfyui/custom_nodes/ComfyUI-Impact-Pack && \
    apt-get update && apt-get install -y libgl1 libglib2.0-0 libsm6 libxrender1 libxext6 && \
    pip install -r requirements.txt && \
    python install.py

RUN git clone https://github.com/ltdrdata/ComfyUI-Impact-Subpack /comfyui/custom_nodes/ComfyUI-Impact-Subpack && \
    cd /comfyui/custom_nodes/ComfyUI-Impact-Subpack && \
    pip install -r requirements.txt && \
    python install.py

RUN git clone https://github.com/BadCafeCode/masquerade-nodes-comfyui.git /comfyui/custom_nodes/masquerade-nodes-comfyui

# Use Gazai's MTB node since the original one takes too long to compile due to the numba issue.
RUN git clone https://github.com/gazai-io/comfy_mtb.git /comfyui/custom_nodes/comfy_mtb && \
    cd /comfyui/custom_nodes/comfy_mtb && \
    pip install -r requirements.txt

RUN git clone https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite.git /comfyui/custom_nodes/ComfyUI-VideoHelperSuite && \
    cd /comfyui/custom_nodes/ComfyUI-VideoHelperSuite && \
    pip install -r requirements.txt

RUN git clone https://github.com/ComfyUI-Workflow/ComfyUI-OpenAI /comfyui/custom_nodes/ComfyUI-OpenAI && \
    cd /comfyui/custom_nodes/ComfyUI-OpenAI && \
    pip install -r requirements.txt

RUN git clone https://github.com/WASasquatch/was-node-suite-comfyui /comfyui/custom_nodes/was-node-suite-comfyui && \
    cd /comfyui/custom_nodes/was-node-suite-comfyui && \
    pip install -r requirements.txt

RUN git clone https://github.com/ramyma/A8R8_ComfyUI_nodes.git /comfyui/custom_nodes/A8R8_ComfyUI_nodes

RUN git clone https://github.com/M1kep/ComfyLiterals.git /comfyui/custom_nodes/ComfyLiterals

RUN git clone https://github.com/1038lab/ComfyUI-RMBG /comfyui/custom_nodes/ComfyUI-RMBG && \
    cd /comfyui/custom_nodes/ComfyUI-RMBG && \
    pip install -r requirements.txt

RUN git clone https://github.com/Fannovel16/comfyui_controlnet_aux.git /comfyui/custom_nodes/comfyui_controlnet_aux && \
    cd /comfyui/custom_nodes/comfyui_controlnet_aux && \
    pip install -r requirements.txt

RUN pip install -U "huggingface_hub[cli]" && \
    pip install -U hf_transfer && \
    export HF_HUB_ENABLE_HF_TRANSFER=1 && \
    huggingface-cli download "LiheYoung/depth_anything_vitl14" && \
    huggingface-cli download "lllyasviel/Annotators" "dpt_hybrid-midas-501f0c75.pt"

# Start container
CMD ["/start.sh"]
